pipeline {
    agent any 

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_IMAGE = "abhishekf5/cicd-e2e"
    }

    stages {
        
        stage('Checkout') {
            steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                    url: 'https://github.com/iam-veeramalla/cicd-end-to-end',
                    branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo "Building Docker Image..."
                    docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
                    '''
                }
            }
        }

        stage('Push the artifacts') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh '''
                        echo "Pushing to DockerHub..."
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker push $DOCKER_IMAGE:$IMAGE_TAG
                        '''
                    }
                }
            }
        }
        
        stage('Checkout K8S manifest SCM') {
            steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                    url: 'https://github.com/iam-veeramalla/cicd-demo-manifests-repo.git',
                    branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        echo "Updating K8S manifest..."
                        sed -i "s/32/$IMAGE_TAG/g" deploy.yaml
                        
                        git config user.email "jenkins@example.com"
                        git config user.name "Jenkins"
                        
                        git add deploy.yaml
                        git commit -m "Updated the deploy yaml | Jenkins Pipeline" || echo "No changes to commit"
                        git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/iam-veeramalla/cicd-demo-manifests-repo.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
