pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "abhishekf5/cicd-e2e"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout SCM') {
            steps {
                git url: 'https://github.com/iam-veeramalla/cicd-end-to-end', branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    echo "Building Docker Image..."
                    sh "docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker') {
            steps {
                script {
                    echo "Pushing Docker Image..."
                    sh "docker login -u <docker-username> -p <docker-password>"
                    sh "docker push ${DOCKER_IMAGE}:${IMAGE_TAG}"
                }
            }
        }
    }
}
